ROSTemplateFormatVersion: '2015-09-01'
Transform: 'Aliyun::Serverless-2018-04-03'
Resources:
  anime-knowledge-graph:  
    Type: 'Aliyun::Serverless::Service' 
    anime-qa:    
      Type: 'Aliyun::Serverless::Function'   
      Properties:     
        Handler: index.handler    
        Initializer: index.initializer 
        InitializationTimeout: 16
        Runtime: python3
        CodeUri: './'
        MemorySize: 256
        Timeout: 16
      Events:
        http-test:
          Type: HTTP
          Properties:
            AuthType: ANONYMOUS
            Methods: ['GET', 'POST']